[package]
name = "meanshift-rs"
version = "0.1.0"
edition = "2018"

[dev-dependencies]
csv = "1.1.6"

[dependencies]
actix = "0.10"
ndarray = "0.14"
ndarray-stats = "0.4"
kdtree = "0.6.0"
num-traits = "0.2.14"
num-integer = "0.1.44"
log = "0.4"
env_logger = "0.8"
futures = "0.3.16"
sorted-vec = "0.5.2"
